{"text_fields":[<?php
function fixChars($str){
	return str_replace(array("’"),array("'"),$str);
}
//set_include_path(get_include_path() . PATH_SEPARATOR . "$_SERVER[DOCUMENT_ROOT]/ZendGdata-1.8.1/library");
set_include_path(get_include_path()."\ZendGdata-1.12.3\library");
include_once("includes/Google_Spreadsheet.php");
$u = "design@lukesnowdon.co.uk";
$p = "minipin13";
$ss = new Google_Spreadsheet($u,$p);
$ss->useSpreadsheet("DrinksCheckerJS");
$ss->useWorksheet("text_fields");
$rows = $ss->getRows();
$output = array();
$output['text_fields'] = array();
foreach($rows as $key){
	$output['text_fields'][$key['id']] = $key['copy'];
}						   
echo json_encode($output['text_fields']);
?>],"drinks": [
        [
            "Beer & cider",
            [
                5,
                2,
                2.5,
                2.8,
                3,
                3.5,
                4,
                4.5,
                5,
                5.5,
                6,
                7,
                8,
                9
            ],
            [
                [
                    "Pint (568ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.568,
                    0.25
                ],
                [
                    "Half pint (284ml)",
                    [
                        1.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.284,
                    0.25
                ],
                [
                    "Can (440ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.44,
                    0.25
                ],
                [
                    "Lge can (500ml)",
                    [
                        3,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.5,
                    0.25
                ],
                [
                    "Bottle (330ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.33,
                    0.25
                ],
                [
                    "Sml bottle (275ml)",
                    [
                        1,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.275,
                    0.25
                ],
                [
                    "Lge bottle (500ml)",
                    [
                        3,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.5,
                    0.25
                ]
            ]
        ],
        [
            "Wine & champagne",
            [
                12,
                3,
                5,
                7,
                9,
                10,
                10.5,
                11,
                11.5,
                12,
                13,
                14,
                15,
                16,
                17
            ],
            [
                [
                    "Std glass (175ml)",
                    [
                        3,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6,
                        7,
                        8,
                        9,
                        10
                    ],
                    0.175,
                    0.72
                ],
                [
                    "Sml glass (125ml)",
                    [
                        2.5,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6,
                        7,
                        8,
                        9,
                        10
                    ],
                    0.125,
                    0.72
                ],
                [
                    "Lge glass (250ml)",
                    [
                        4,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6,
                        7,
                        8,
                        9,
                        10
                    ],
                    0.25,
                    0.72
                ],
                [
                    "Bottle (750ml)",
                    [
                        5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        12,
                        15
                    ],
                    0.75,
                    0.72
                ]
            ]
        ],
        [
            "Fortified wine",
            [
                17.5,
                15,
                17.5,
                18,
                20
            ],
            [
                [
                    "Double (50ml)",
                    [
                        5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6,
                        7,
                        8,
                        9,
                        10
                    ],
                    0.05,
                    1.3
                ]
            ]
        ],
        [
            "Spirits, shots & liqueurs",
            [
                40,
                17,
                21,
                25,
                28,
                30,
                37.5,
                38,
                40
            ],
            [
                [
                    "Single (25ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.025,
                    2.36
                ],
                [
                    "Lge single (35ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.035,
                    2.36
                ],
                [
                    "Double (50ml)",
                    [
                        4,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.05,
                    2.36
                ],
                [
                    "Lge double (70ml)",
                    [
                        5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.07,
                    2.36
                ]
            ],
            [
                "None",
                "Mixer",
                "Diet mixer",
                "Fruit juice",
                "Energy drink"
            ]
        ],
        [
            "Alcopops",
            [
                5,
                4,
                5,
                5.5
            ],
            [
                [
                    "Sml bottle (275ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.275,
                    0.72
                ],
                [
                    "Std bottle (330ml)",
                    [
                        2.5,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.33,
                    0.72
                ],
                [
                    "Lge bottle (750ml)",
                    [
                        3,
                        1,
                        1.5,
                        2,
                        2.5,
                        3,
                        3.5,
                        4,
                        4.5,
                        5,
                        5.5,
                        6
                    ],
                    0.75,
                    0.72
                ]
            ]
        ]
    ]
}
